# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drvfinder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_name', models.CharField(max_length=50, verbose_name='Driver Name')),
                ('driver_picture', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Driver Picture')),
                ('driver_passport_picture', models.ImageField(default='documents/no-img.jpeg', upload_to='documents', verbose_name='Driver Passport Picture')),
                ('driver_phone', models.CharField(blank=True, max_length=200, verbose_name='Driver Phone')),
            ],
            options={
                'verbose_name_plural': 'Promoter Details',
            },
        ),
    ]
