# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-12 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drvfinder', '0002_driver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='driver',
            options={'verbose_name_plural': 'Driver Details'},
        ),
    ]
